# Node 2 config - MIDDLE node-id
# Security enabled for auth tests

service {
	node-id a2
	user root
	group root
	proto-fd-max 15000
	cluster-name smd-sync-test
	feature-key-file /etc/aerospike/features.conf
}

logging {
	console {
		context any info
		context smd debug
		context exchange debug
	}
	file /var/log/aerospike/aerospike.log {
		context any info
		context smd debug
		context exchange debug
		context fabric warning
	}
}

network {
	service {
		address any
		port 3000
	}

	heartbeat {
		mode mesh
		mesh-seed-address-port smd-sync-test-aerospike-1 3004
		mesh-seed-address-port smd-sync-test-aerospike-2 3004
		mesh-seed-address-port smd-sync-test-aerospike-3 3004
		port 3004
		interval 150
		timeout 10
	}

	fabric {
		port 3001
	}
}

security {
}

namespace test {
	replication-factor 2
	default-ttl 1d
	nsup-period 120
	storage-engine memory {
		data-size 512M
	}
}
