# Aerospike database configuration file.

# This stanza must come first.
service {
	user root
	group root
	proto-fd-max 15000
	cluster-name docker-compose-cluster
	feature-key-file /etc/aerospike/features.conf
}

logging {
	console {
		context any info
	}
}

network {
	service {
		address any
		port 3000
	}

	heartbeat {
		mode mesh
		# All replicas will seed from aerospike-1, aerospike-2, aerospike-3
		mesh-seed-address-port docker-aerospike-1 3004
		mesh-seed-address-port docker-aerospike-2 3004
		mesh-seed-address-port docker-aerospike-3 3004
		port 3004
		interval 150
		timeout 10
	}

	fabric {
		port 3001
	}
}


namespace test {
	replication-factor 3
	default-ttl 5d
	nsup-period 120
	strong-consistency true
	storage-engine memory {
		data-size 1G
	}
}
